"""
This type stub file was generated by pyright.
"""

import sys
import os
import importlib
import types
from pkgutil import extend_path
from . import _gi
from ._gi import PyGIDeprecationWarning, PyGIWarning, Repository, _API

__path__ = ...
_static_binding_error = ...
if 'gobject' in sys.modules:
    ...
_versions = ...
_overridesdir = ...
_gobject = ...
version_info = ...
__version__ = ...
class _DummyStaticModule(types.ModuleType):
    __path__ = ...
    def __getattr__(self, name):
        ...
    


def check_version(version): # -> None:
    ...

def require_version(namespace, version): # -> None:
    """ Ensures the correct versions are loaded when importing `gi` modules.

    :param namespace: The name of module to require.
    :type namespace: str
    :param version: The version of module to require.
    :type version: str
    :raises ValueError: If module/version is already loaded, already required, or unavailable.

    :Example:

    .. code-block:: python

        import gi
        gi.require_version('Gtk', '3.0')

    """
    ...

def require_versions(requires): # -> None:
    """ Utility function for consolidating multiple `gi.require_version()` calls.

    :param requires: The names and versions of modules to require.
    :type requires: dict

    :Example:

    .. code-block:: python

        import gi
        gi.require_versions({'Gtk': '3.0', 'GLib': '2.0', 'Gio': '2.0'})
    """
    ...

def get_required_version(namespace): # -> None:
    ...

def require_foreign(namespace, symbol=...): # -> None:
    """Ensure the given foreign marshaling module is available and loaded.

    :param str namespace:
        Introspection namespace of the foreign module (e.g. "cairo")
    :param symbol:
        Optional symbol typename to ensure a converter exists.
    :type symbol: str or None
    :raises: ImportError

    :Example:

    .. code-block:: python

        import gi
        import cairo
        gi.require_foreign('cairo')

    """
    ...

