"""
This type stub file was generated by pyright.
"""

class GError(RuntimeError):
    def __init__(self, message=..., domain=..., code=...) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def copy(self): # -> GError:
        ...
    
    def matches(self, domain, code):
        """Placeholder that will be monkey patched in GLib overrides."""
        ...
    
    @staticmethod
    def new_literal(domain, message, code):
        """Placeholder that will be monkey patched in GLib overrides."""
        ...
    


