"""
This type stub file was generated by pyright.
"""

repository = ...
_introspection_modules = ...
def get_parent_for_object(object_info): # -> type[object] | Any:
    ...

def get_interfaces_for_object(object_info): # -> list[Any]:
    ...

class IntrospectionModule:
    """An object which wraps an introspection typelib.

    This wrapping creates a python module like representation of the typelib
    using gi repository as a foundation. Accessing attributes of the module
    will dynamically pull them in and create wrappers for the members.
    These members are then cached on this introspection module.
    """
    def __init__(self, namespace, version=...) -> None:
        """Might raise gi._gi.RepositoryError"""
        ...
    
    def __getattr__(self, name): # -> type[__class_GObjectMeta] | type[__class_StructMeta]:
        ...
    
    def __repr__(self): # -> LiteralString:
        ...
    
    def __dir__(self): # -> list[str]:
        ...
    


def get_introspection_module(namespace): # -> IntrospectionModule:
    """
    :Returns:
        An object directly wrapping the gi module without overrides.

    Might raise gi._gi.RepositoryError
    """
    ...

